name: sudoku_game
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  sudoku_dart: ^1.2.0
  logger: ^2.4.0
  sprintf: ^7.0.0
  scoped_model: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  just_audio: ^0.9.40
  camera_android_camerax: 0.6.8+3
  camera: 0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  image: ^4.2.0
  yaml: ^3.1.2
  tflite_flutter: ^0.11.0
  opencv_dart: ^1.2.4
  # opencv_dart: 
    # git:
    #   url: https://github.com/einsitang/opencv_dart.git
    #   ref: 452994e8868b4d1f547d515cb89b53f0037840ec
  # firebase_core: ^3.3.0
  firebase_core: ^3.4.1
  # firebase_analytics: ^10.0.2
  firebase_analytics: ^11.3.1
  # firebase_crashlytics: ^3.2.0
  firebase_crashlytics: ^4.1.1
  # firebase_performance: ^3.0.0
  firebase_performance: ^0.10.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.4

  
  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/image/
    - assets/audio/
    - assets/tf_model/sudoku/
    - assets/tf_model/digits/

 