name: sudoku_game
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.0.0+4

environment:
  sdk: ^3.5.2

dependencies:
  camera: 0.11.0+2
  camera_android_camerax: 0.6.8+3
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.3.1
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.1
  firebase_performance: ^0.10.0+6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^5.2.0
  image: ^4.2.0
  intl: ^0.19.0
  just_audio: ^0.9.40
  logger: ^2.4.0
  modal_bottom_sheet: ^3.0.0
  opencv_dart: ^1.2.4
  path: ^1.9.0
  path_provider: ^2.1.4
  rename_app: ^1.6.1
  scoped_model: ^2.0.0
  sprintf: ^7.0.0
  sudoku_dart: ^1.2.0
  tflite_flutter: ^0.11.0
  url_launcher: ^6.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/sudoku_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  background_color: "#000000"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/image/
    - assets/audio/
    - assets/tf_model/sudoku/
    - assets/tf_model/digits/
