// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQcyIP6cin3iPf44tW6BDRnkS26zYVCVw',
    appId: '1:239052411472:android:f7bda6b4dd67be65b43755',
    messagingSenderId: '239052411472',
    projectId: 'sudoku-game-bc4b0',
    storageBucket: 'sudoku-game-bc4b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6VoLSP7rcgOWJ22JhFeELbykIrIaxrTA',
    appId: '1:239052411472:ios:70c818821d8f92c7b43755',
    messagingSenderId: '239052411472',
    projectId: 'sudoku-game-bc4b0',
    storageBucket: 'sudoku-game-bc4b0.appspot.com',
    iosBundleId: 'com.example.sudokuGame',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxaryeMmOEP1czgSg9TIx_BY06JjeD1n0',
    appId: '1:239052411472:web:9e6b8f5981bb92e8b43755',
    messagingSenderId: '239052411472',
    projectId: 'sudoku-game-bc4b0',
    authDomain: 'sudoku-game-bc4b0.firebaseapp.com',
    storageBucket: 'sudoku-game-bc4b0.appspot.com',
    measurementId: 'G-036RZ0MSTT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6VoLSP7rcgOWJ22JhFeELbykIrIaxrTA',
    appId: '1:239052411472:ios:70c818821d8f92c7b43755',
    messagingSenderId: '239052411472',
    projectId: 'sudoku-game-bc4b0',
    storageBucket: 'sudoku-game-bc4b0.appspot.com',
    iosBundleId: 'com.example.sudokuGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxaryeMmOEP1czgSg9TIx_BY06JjeD1n0',
    appId: '1:239052411472:web:176547c169d27ad8b43755',
    messagingSenderId: '239052411472',
    projectId: 'sudoku-game-bc4b0',
    authDomain: 'sudoku-game-bc4b0.firebaseapp.com',
    storageBucket: 'sudoku-game-bc4b0.appspot.com',
    measurementId: 'G-0DVRBMF3WC',
  );

}